image: maven:3.3.9-jdk-7
pipelines:
  branches:
    qa:
      - step:
          script:
            # AWS credentials should be stored in the repository's settings, under the "Environment Variables" section.
            # Be sure to check the "secured" box when you add them.
            - pipeline_tools/run_build.sh "mvn clean install  -Dcrx.host=52.70.60.188 -Dcrx.port=4502 -Dcrx.userId=admin -Dcrx.password=$AEM_QA -PautoInstallPackage -U" i-091f350e58b9e7439 "$AWS_ACCESS_KEY" "$AWS_SECRET_ACCESS_KEY"

            - pipeline_tools/run_build.sh "mvn clean install  -Dcrx.host=54.82.49.118 -Dcrx.port=4503 -Dcrx.userId=admin -Dcrx.password=$AEM_QA -PautoInstallPackage -U" i-0e76466360e07612a "$AWS_ACCESS_KEY" "$AWS_SECRET_ACCESS_KEY"

    stage:
      - step:
          script:
            - pipeline_tools/run_build.sh "mvn clean install  -Dcrx.host=52.73.137.109 -Dcrx.port=4502 -Dcrx.userId=admin -Dcrx.password=$AEM_STG -PautoInstallPackage -U" i-0e3efa800b42a3daa "$AWS_ACCESS_KEY" "$AWS_SECRET_ACCESS_KEY"

            - pipeline_tools/run_build.sh "mvn clean install  -Dcrx.host=54.86.79.28 -Dcrx.port=4503 -Dcrx.userId=admin -Dcrx.password=$AEM_STG -PautoInstallPackage -U" i-0c863f7f700d11f56 "$AWS_ACCESS_KEY" "$AWS_SECRET_ACCESS_KEY"

            - pipeline_tools/run_build.sh "mvn clean install  -Dcrx.host=54.87.1.169 -Dcrx.port=4503 -Dcrx.userId=admin -Dcrx.password=$AEM_STG -PautoInstallPackage -U" i-0766350f17a41692c "$AWS_ACCESS_KEY" "$AWS_SECRET_ACCESS_KEY"

    master:
      - step:
          script:
            - pipeline_tools/run_build.sh "mvn clean install  -Dcrx.host=52.73.137.109 -Dcrx.port=4502 -Dcrx.userId=admin -Dcrx.password=$AEM_STG -PautoInstallPackage -U" i-0e3efa800b42a3daa "$AWS_ACCESS_KEY" "$AWS_SECRET_ACCESS_KEY"

            - pipeline_tools/run_build.sh "mvn clean install  -Dcrx.host=54.86.79.28 -Dcrx.port=4503 -Dcrx.userId=admin -Dcrx.password=$AEM_STG -PautoInstallPackage -U" i-0c863f7f700d11f56 "$AWS_ACCESS_KEY" "$AWS_SECRET_ACCESS_KEY"

            - pipeline_tools/run_build.sh "mvn clean install  -Dcrx.host=54.87.1.169 -Dcrx.port=4503 -Dcrx.userId=admin -Dcrx.password=$AEM_STG -PautoInstallPackage -U" i-0766350f17a41692c "$AWS_ACCESS_KEY" "$AWS_SECRET_ACCESS_KEY"

    systems-build:
      - step:
          script:
            - pipeline_tools/run_build.sh "mvn clean install  -Dcrx.host=52.2.152.26 -Dcrx.port=4502 -Dcrx.userId=admin -Dcrx.password=$AEM_PROD -PautoInstallPackage -U" i-0bcb3415c346ed06a "$AWS_ACCESS_KEY" "$AWS_SECRET_ACCESS_KEY"

            - pipeline_tools/run_build.sh "mvn clean install  -Dcrx.host=54.88.41.184 -Dcrx.port=4503 -Dcrx.userId=admin -Dcrx.password=$AEM_PROD -PautoInstallPackage -U" i-0d0e2e4efe639c469 "$AWS_ACCESS_KEY" "$AWS_SECRET_ACCESS_KEY"

            - pipeline_tools/run_build.sh "mvn clean install  -Dcrx.host=54.88.71.84 -Dcrx.port=4503 -Dcrx.userId=admin -Dcrx.password=$AEM_PROD -PautoInstallPackage -U" i-09a655bca172c5f54 "$AWS_ACCESS_KEY" "$AWS_SECRET_ACCESS_KEY"